# Generated by Django 4.1.2 on 2022-12-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=64, verbose_name='Management Company')),
                ('address', models.CharField(max_length=64)),
                ('apartment', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64, null=True)),
                ('zip_code', models.IntegerField(null=True, verbose_name='Zip Code')),
                ('state', models.CharField(choices=[('New York', 'New York'), ('New York', 'New Jersey')], default='NEW YORK', max_length=12)),
                ('appliance', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=12, null=True, verbose_name='Phone Number')),
                ('comments', models.TextField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
