# Generated by Django 4.1.2 on 2022-12-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='private',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=12),
        ),
    ]
