# Generated by Django 4.1.2 on 2022-12-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0006_alter_work_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('New York', 'New York'), ('New York', 'New Jersey')], default='Pending', max_length=12),
        ),
    ]
