# Generated by Django 4.1.2 on 2022-12-16 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0009_work_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='created_at',
        ),
        migrations.AddField(
            model_name='work',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 16, 16, 22, 56, 643762, tzinfo=datetime.timezone.utc)),
        ),
    ]
