# Generated by Django 4.1.2 on 2022-12-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0010_remove_work_created_at_work_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='date',
        ),
    ]
