# Generated by Django 4.1.2 on 2022-12-20 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0013_appliance_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliance',
            old_name='part',
            new_name='part_name',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='address',
        ),
        migrations.AddField(
            model_name='work',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appliance_to_service', to='fmc.appliance'),
        ),
    ]
