# Generated by Django 4.1.2 on 2022-12-21 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0014_rename_part_appliance_part_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='part',
        ),
        migrations.AddField(
            model_name='appliance',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appliance_to_service', to='fmc.work'),
        ),
    ]
