# Generated by Django 4.1.2 on 2022-12-21 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0015_remove_work_part_appliance_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliance',
            name='order',
        ),
        migrations.AddField(
            model_name='work',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appliance_to_service', to='fmc.appliance'),
        ),
    ]
