# Generated by Django 4.1.2 on 2022-12-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0016_remove_appliance_order_work_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='part',
        ),
        migrations.AddField(
            model_name='work',
            name='part',
            field=models.ManyToManyField(null=True, related_name='appliance_to_service', to='fmc.appliance'),
        ),
    ]
