# Generated by Django 4.1.2 on 2022-12-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0018_remove_work_part_work_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='add_game',
            field=models.ManyToManyField(blank=True, related_name='add_game', to='fmc.appliance'),
        ),
    ]
