# Generated by Django 4.1.2 on 2022-12-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0019_work_add_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='add_game',
        ),
    ]
