# Generated by Django 4.1.2 on 2022-12-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0020_remove_work_add_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='address_parts',
            field=models.ManyToManyField(blank=True, related_name='add_game', to='fmc.appliance'),
        ),
    ]
