# Generated by Django 4.1.2 on 2022-12-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0021_work_address_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='address_parts',
            field=models.ManyToManyField(blank=True, related_name='address_parts', to='fmc.appliance'),
        ),
    ]
