# Generated by Django 4.1.2 on 2022-12-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0023_rename_address_parts_work_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='part',
        ),
    ]
