# Generated by Django 4.1.2 on 2022-12-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0024_remove_work_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='product',
        ),
        migrations.DeleteModel(
            name='Appliance',
        ),
    ]
