# Generated by Django 4.1.2 on 2022-12-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0025_remove_work_product_delete_appliance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=64, null=True)),
                ('model_number', models.CharField(max_length=64, null=True)),
                ('part_number', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
