# Generated by Django 4.1.2 on 2022-12-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0026_appliances'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='part',
            field=models.ManyToManyField(blank=True, related_name='add_part', to='fmc.appliances'),
        ),
    ]
