# Generated by Django 4.1.2 on 2022-12-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0027_work_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliances',
            name='appliance',
            field=models.CharField(max_length=64, null=64),
            preserve_default=64,
        ),
    ]
