# Generated by Django 4.1.2 on 2022-12-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0028_appliances_appliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliances',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
