# Generated by Django 4.1.2 on 2022-12-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0029_appliances_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliances',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
