# Generated by Django 4.1.2 on 2022-12-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0031_remove_work_part_appliances_part'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliances',
            old_name='part',
            new_name='service_address',
        ),
    ]
