# Generated by Django 4.1.2 on 2022-12-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0032_rename_part_appliances_service_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliances',
            name='service_address',
        ),
        migrations.AddField(
            model_name='work',
            name='part',
            field=models.ManyToManyField(blank=True, related_name='add_part', to='fmc.appliances'),
        ),
    ]
