# Generated by Django 4.1.2 on 2022-12-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0033_remove_appliances_service_address_work_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
