# Generated by Django 4.1.2 on 2022-12-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0037_appliances'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliances',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
