# Generated by Django 4.1.2 on 2022-12-28 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0038_appliances_date_added_work_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliances',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_appliances', to='fmc.work'),
        ),
    ]
