# Generated by Django 4.1.2 on 2022-12-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0039_alter_appliances_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliances',
            name='appliance',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
