# Generated by Django 4.1.2 on 2022-12-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0040_alter_appliances_appliance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliances',
            old_name='address',
            new_name='part_address',
        ),
    ]
