# Generated by Django 4.1.2 on 2022-12-28 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0042_alter_appliances_part_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliances',
            name='part_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_appliances', to='fmc.work'),
        ),
    ]
