# Generated by Django 4.1.2 on 2023-01-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0043_alter_appliances_part_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='phone',
            field=models.CharField(max_length=64, null=True, verbose_name='Phone Number'),
        ),
    ]
