# Generated by Django 4.1.5 on 2023-01-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fmc", "0044_alter_work_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="zip_code",
            field=models.IntegerField(blank=True, null=True, verbose_name="Zip Code"),
        ),
    ]
