# Generated by Django 4.1.5 on 2023-01-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fmc", "0045_alter_work_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="comments",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
