# Generated by Django 4.0.6 on 2023-01-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0046_alter_work_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='work',
            name='zip_code',
            field=models.IntegerField(null=True, verbose_name='Zip Code'),
        ),
    ]
