# Generated by Django 4.1.2 on 2023-01-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0047_work_logo_alter_work_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='comments',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Description'),
        ),
    ]
