# Generated by Django 4.0.6 on 2023-01-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0048_alter_work_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Phone Number'),
        ),
    ]
