# Generated by Django 4.0.6 on 2023-01-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0049_alter_work_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='requested',
            field=models.DateField(blank=True, null=True),
        ),
    ]
