# Generated by Django 4.0.6 on 2023-01-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0050_work_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zip Code'),
        ),
    ]
