# Generated by Django 4.0.6 on 2023-02-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0051_alter_work_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='completed',
            field=models.DateField(blank=True, null=True, verbose_name='Date Complete'),
        ),
        migrations.AlterField(
            model_name='work',
            name='private',
            field=models.CharField(choices=[('Canela', 'Canela'), ('Eddie', 'Eddie'), ('Jansel', 'Jansel'), ('Jose', 'Jose'), ('Luis', 'Luis'), ('Oscar A.', 'Oscar A.'), ('Oscar', 'Oscar')], default='', max_length=12),
        ),
    ]
