# Generated by Django 4.0.6 on 2023-02-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmc', '0052_work_completed_alter_work_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='complete_by',
            field=models.CharField(choices=[('Canela', 'Canela'), ('Eddie', 'Eddie'), ('Jansel', 'Jansel'), ('Jose', 'Jose'), ('Luis', 'Luis'), ('Oscar A.', 'Oscar A.'), ('Oscar', 'Oscar')], default='', max_length=12, verbose_name='Complete By'),
        ),
        migrations.AlterField(
            model_name='work',
            name='private',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=12),
        ),
    ]
